esg/urls.py
from django.contrib import admin
from django.urls import path, include
from pfreers import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pfreers/', include('pfreers.urls')),
    path('', include('pfreers.urls'))
]

pfreers/urls.py
from django.urls import path
from . import views

app_name = 'pfreers'

urlpatterns = [
    path('', views.index, name='index'),
    #path('<int:PfreeEateries_id>/', views.detail),
    path('create/', views.PfreeEateries_create, name='PfreeEateries_create'),
    path('update/', views.PfreeEateries_update, name='PfreeEateries_update'),
]

pfreers/models.py
from django.db import models

# Create your models here.

class PfreeEateries(models.Model):
    KOREANFOOD = 'KF'
    SNACK = 'SN'
    CHICKEN = 'CH'
    PIZZA = 'PI'
    CHINESEFOOD = 'CF'
    FASTFOOD = "FF"
    BOSSAM = 'BO'
    HOTSOUP = 'HS'
    EATERY_TYPES_CHOICES = [
        (KOREANFOOD, 'Koreanfood'),
        (SNACK, 'Snack'),
        (CHICKEN, 'Chicken'),
        (PIZZA, 'Pizza'),
        (CHINESEFOOD, 'Chinesefood'),
        (FASTFOOD, "Fastfood"),
        (BOSSAM, 'Bossam'),
        (HOTSOUP, 'Hotsoup'), 
    ]
    eatery_types = models.CharField(max_length=2, choices=EATERY_TYPES_CHOICES, default='KOREANFOOD')
    def is_upperclass(self):
        return self.eatery_types in {self.KOREANFOOD, self.SNACK, self.CHICKEN, self.PIZZA, self.CHINESEFOOD, self.FASTFOOD, self.BOSSAM, self.HOTSOUP}
    eatery = models.CharField(max_length=50)
    echolv = models.CharField(max_length=10)
    echof_co_cnt = models.CharField(max_length=10)
    perf = models.CharField(max_length=10)
    create_date = models.DateTimeField()

pfreers/forms.py
from django import forms
from pfreers.models import PfreeEateries

class PfreeEateriesForm(forms.ModelForm):
    class Meta:
        model = PfreeEateries
        #fields = ['eatery_types', 'eatery', 'echolv', 'perf']
        fields = ['eatery_types', 'eatery']
        widgets = {
            'eatery': forms.TextInput(attrs={'class':'form-control'}),
            #'echolv': forms.TextInput(attrs={'class':'form-control'}),
            #'perf': forms.TextInput(attrs={'class':'form-control'}),
        }

pfreers/views.py
import types
from django.core import paginator
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse
from .models import PfreeEateries
from django.utils import timezone 
from .forms import PfreeEateriesForm
from datetime import datetime
from django.core.paginator import Paginator

import json
from decouple import config
import pandas as pd
from pandas import DataFrame
from pprint import pprint as pp
from simple_salesforce import Salesforce, SalesforceLogin, SFType

def index(request):
    """
    Output for PfreeEateries
    """
    # page count
    page = request.GET.get('page', '1')

    # query
    qry = 'SELECT Id, eatery_types__C, eatery_name__C, echo_level__c, echof_cont_cnt__c, perf_rate__C, join_date__c FROM pfree_eatery__c ORDER BY Id DESC'
    #PfreeEateries_list = PfreeEateries.objects.order_by('-create_date')
    
    qr = SOQL(qry)
    PfreeEateries_list = qr.values

    #print(PfreeEateries_list)

    # handling pages
    paginator = Paginator(PfreeEateries_list, 10) # Show 10 per page
    page_obj = paginator.get_page(page)
    #print(data)
    #context = {'PfreeEateries_list': PfreeEateries_list}
    context = {'PfreeEateries_list': page_obj}
    return render(request, 'pfreers/pfreeElist.html', context)

def detail(request, PfreeEateries_id):
    """
    List of PfreeEateries
    """
    elist = PfreeEateries.objects.get(id=PfreeEateries_id)
    context = {'elist': elist}
    return render(request, 'pfreers/pfreeElist_detail.html', context)

def PfreeEateries_create(request):
    """
    Register a eatery
    """
    '''
            PfreeEateries = form.save(commit=False)
            PfreeEateries.echolv = 'BLUE'
            PfreeEateries.perf = 0
            PfreeEateries.create_date = today.isoformat()+'Z'
            PfreeEateries.save()
    '''
    username = config('username')
    password = config('password')
    security_token = config('security_token')
    domain = 'login'

    #sf = Salesforce(username=username, password=password, security_token=security_token, domain=domain)
    session_id, instance = SalesforceLogin(username=username, password=password, security_token=security_token, domain=domain)
    #sf = Salesforce(instance_url='http://'+instance , session_id=session_id)
    #sf = Salesforce(instance=instance , session_id=session_id)

    pfree_eatery__c = SFType('pfree_eatery__c', session_id, instance)
    ecount = 0
    prate = 0
    if request.method == 'POST':
        #form = PfreeEateriesForm(request.POST)
        etypes = request.POST['eatery_types']
        name = request.POST['eatery_name']
        today = timezone.now()
 
        data = {
            'eatery_types__c' : etypes,
            'eatery_name__c' : name,
            'echo_level__c' : 'BLUE',
            'echof_cont_cnt__c' : ecount,
            'perf_rate__c' : prate,
            'join_date__c' : today.isoformat() + 'Z'
        }
        response = pfree_eatery__c.create(data)
        print(response)
        return redirect('/pfreers/')
    else:
        form = PfreeEateriesForm()
        context = {'form': form}
        return render(request, 'pfreers/PfreeEateries_form.html', context)

def PfreeEateries_update(request):

    username = config('username')
    password = config('password')
    security_token = config('security_token')
    domain = 'login'

    session_id, instance = SalesforceLogin(username=username, password=password, security_token=security_token, domain=domain)

    pfree_eatery__c = SFType('pfree_eatery__c', session_id, instance)
    
    if request.method == 'GET':
        Id = request.GET['Id']
        #Id = 'a0G5g0000016B5c'
        # query
        qry = "SELECT Id, eatery_types__C, eatery_name__C, echo_level__c, echof_cont_cnt__c, perf_rate__C, join_date__c FROM pfree_eatery__c" + " where Id='" + Id + "'"
    
        qr = SOQL(qry)

        print(qr['echof_cont_cnt__c'].values[0])
        '''
        print(qr['echo_level__c'].values[0])
        print(qr['perf_rate__c'].values[0])
        '''
        ecount = qr['echof_cont_cnt__c'].values[0] + 20
        print(ecount)

        if (ecount >=2500):
            print("Your level is PLATINUM")
            elevel = 'PLATINUM'
        elif (ecount >= 1500):
            print("Your level is GOLD")
            elevel = 'GOLD'
        elif (ecount >= 1000):
            print("Your level is SILVER")
            elevel = 'SILVER'
        elif (ecount >= 500):
            print("Your level is BRONZE")
            elevel = 'BRONZE'
        else:
            print("Your level is BLUE")
            elevel = 'BLUE'

        prate = (ecount/2500) * 100
        print(elevel)
        print(prate)

        update_data = {}
        update_data['echo_level__c'] = elevel
        update_data['perf_rate__c'] = prate
        update_data['echof_cont_cnt__c'] = ecount

        response = pfree_eatery__c.update(Id, update_data)        
        print(response) 
        
    return HttpResponse("Your request has been processed.")

def SOQL(SOQL):
    username = config('username')
    password = config('password')
    security_token = config('security_token')
    domain = 'login'

    #sf = Salesforce(username=username, password=password, security_token=security_token, domain=domain)
    session_id, instance = SalesforceLogin(username=username, password=password, security_token=security_token, domain=domain)
    #sf = Salesforce(instance_url='http://'+instance , session_id=session_id)
    sf = Salesforce(instance=instance , session_id=session_id)
    
    qryResult = sf.query(SOQL)
    print('Record count {0}'.format(qryResult['totalSize']))
    isDone = qryResult['done']
    
    if isDone == True:
        df = DataFrame(qryResult['records'])
    while isDone != True:
        try:
            if qryResult['done'] != True:
                df = df.append(DataFrame(qryResult['records']))
                qryResult = sf.query_more(qryResult['nextRecorsdUrl'], True)
            else:
                df = df.append(DataFrame(qryResult['records']))
                isDone = True
                print('Completed')
                break
            
        except NameError:
            df = DataFrame(qryResult['records'])
            qry = sf.query_more(qryResult['nextRecordsUrl'], True)        
    
    df = df.drop('attributes', axis = 1)
    return df;

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <!-- Requried meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width", initial-scale=1, shrink-to-fit=no">
        <!-- Boodstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- pfreers CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
        <title>pfreers site of baemin</title>
    </head>
    <body>
        <!-- 기본 템플릿에 삽입될 내용 시작-->
        {% block content %}
        {% endblock %}
        <!-- 기본 템플릿에 삽입될 내용 끝-->
    </body>
</html>

templates/pfreers/PfreeEateries_form copy.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Register a eatery</h5>
    <form method='post' class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">save</button>
    </form>
</div>
{% endblock %}

templates/pfreers/PfreeEateries_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Register an eatery</h5>
    <form method='post' class="post-form my-3">
        {% csrf_token %}
        Eatery types: <select name="eatery_types">
                        <option value="KF">Koreanfood</option>
                        <option value="CF">Chinesefood</option>
                        <option value="CH">Chicken</option>
                        <option value="PI">Pizza</option>
                        <option value="SN">Snack</option>
                        <option value="BO">Bossam</option>
                        <option value="FF">Fastfood</option>
                        <option value="HS">Hotsoup</option>
                      </select><br><br>
        Eatery name : <input type="text" name="eatery_name"><br>
        <button type="submit" class="btn btn-primary">save</button>
    </form>
</div>
{% endblock %}

templates/pfreers/pfreeElist copy.html
<html>
    <head> 
        <title>Baemin ESG :: Home</title> <meta charset="utf-8"> 
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <!-- CSS --> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> 
        <!-- JS --> 
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> 
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script> 
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> 
    </head>
<body>

{% load static %}
<div class="jumbotron text-center"> 
    <img src="{% static 'BAEMIN.png' %}" alt="baemin logo" height="140" width="100"><h1>BAEMIN ESG Homepage</h1> 
    <p>지구가 플라스틱으로부터 자유로와 질때까지 우리의 노력은 계속됩니다.</p> 
</div> 

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
{% load pfreers_filter %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>음식점 분류</th>
            <th>음식점 명</th>
            <th>에코 등급</th>
            <th>에코용기 판매 개수</th>
            <th>성과율</th>
            <th>등록일시</th>
        </tr>
        </thead>
        <tbody>
        {% if PfreeEateries_list %}
        {% for elist in PfreeEateries_list %}
        <tr>
            <td>{{ PfreeEateries_list.paginator.count|sub:PfreeEateries_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>{{ elist.eatery_types__c }}</td>
            <td>{{ elist.eatery_name__c }}</td>
            <td>{{ elist.echo_level__c }}</td>
            <td>{{ elist.echof_cont_cnt__c }}</td>
            <td>{{ elist.perf_rate__c }}%</td>
            <td>{{ elist.join_date__c }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">등록된 음식점 리스트가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- Start paging processing -->
    <ul class="pagination justify-content-center">
        <!-- Previous page-->
        {% if PfreeEateries_list.has_previous %}
        <li class="page_item">
            <a class="page-link" href="?page={{ PfreeEateries_list.previous_page_number }}">previous</a>
        </li>
        {% endif %}
        <!-- Page list -->
        {% for page_number in PfreeEateries_list.paginator.page_range %}
        {% if page_number >= PfreeEateries_list.number|add:-5 and page_number <= PfreeEateries_list.number|add:5 %}
            {% if page_number == PfreeEateries_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- Next page -->
        {% if PfreeEateries_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ PfreeEateries_list.next_page_number }}">next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">next</a>
        </li>
        {% endif %}
    </ul>
    <!-- End paging processing -->

    <a href="{% url 'pfreers:PfreeEateries_create' %}" class="btn btn-primary">Register a eatery</a>
</div>
</body>
</html>

templates/pfreers/pfreeElist.html
<html>
    <head> 
        <title>Baemin ESG :: Home</title> <meta charset="utf-8"> 
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <!-- CSS --> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> 
        <!-- JS --> 
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> 
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script> 
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> 
    </head>
<body>

{% load static %}
<div class="jumbotron text-center"> 
    <img src="{% static 'BAEMIN.png' %}" alt="baemin logo" height="140" width="100"><h1>BAEMIN ESG Homepage</h1> 
    <p>Our efforts will continue until the planet is free from plastic.</p> 
</div> 

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
{% load pfreers_filter %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>Number</th>
            <th>Eatery types</th>
            <th>Eatery name</th>
            <th>Echo level</th>
            <th>Eco container sold count</th>
            <th>Perf rate</th>
            <th>Join date</th>
        </tr>
        </thead>
        <tbody>
        {% if PfreeEateries_list %}
        {% for elist in PfreeEateries_list %}
        <tr>
            <td>{{ PfreeEateries_list.paginator.count|sub:PfreeEateries_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>{{ elist.1 }}</td>
            <td>{{ elist.2 }}</td>
            <td>{{ elist.3 }}</td>
            <td>{{ elist.4 }}</td>
            <td>{{ elist.5 }}%</td>
            <td>{{ elist.6 }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">There is no list of registered eateries.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- Start paging processing -->
    <ul class="pagination justify-content-center">
        <!-- Previous page-->
        {% if PfreeEateries_list.has_previous %}
        <li class="page_item">
            <a class="page-link" href="?page={{ PfreeEateries_list.previous_page_number }}">previous</a>
        </li>
        {% endif %}
        <!-- Page list -->
        {% for page_number in PfreeEateries_list.paginator.page_range %}
        {% if page_number >= PfreeEateries_list.number|add:-5 and page_number <= PfreeEateries_list.number|add:5 %}
            {% if page_number == PfreeEateries_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- Next page -->
        {% if PfreeEateries_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ PfreeEateries_list.next_page_number }}">next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">next</a>
        </li>
        {% endif %}
    </ul>
    <!-- End paging processing -->

    <a href="{% url 'pfreers:PfreeEateries_create' %}" class="btn btn-primary">Register an eatery</a>
</div>
</body>
</html>

templates/pfreers/pfreeElist_detail.html
<h1> {{ elist.eatery }}</h1>

<div>
    {{ elist.echolv }}
</div>